### ISSUE TITLE
Can't find config from stable version & nightly doesn't run

### ISSUE THREAD

**Issue by jpenguin** [guysoft/PleromaPi#1]
I got the stable build up and running & created the admin user.  There is no "/var/lib/pleroma/config.exs"  I have no idea where the config file is to enable the admin panel

Next, I tried the latest nightly image.  The make_admin_user script says, 
`Error: No such container: pleroma`

```
pi@pleromapi:~ $ systemctl status docker-compose
● docker-compose.service - docker-compose service
   Loaded: loaded (/etc/systemd/system/docker-compose.service; enabled; vendor p
   Active: inactive (dead)
```

**Comment by guysoft** [comment]
config.exs is located at: ``/boot/docker-compose/02_pleromavolumes/pleroma/config.exs``

**Comment by guysoft** [comment]
Did you figure out what to do?

**Comment by jpenguin** [comment]
Ya, a while ago actually.  Thanks.  I was going through github and found a couple issues I forgot to close
