### ISSUE TITLE
(MatchError) no match of right hand side value: {[assume_yes: true], ["–admin"], []}

### ISSUE THREAD

**Issue by litecave** [guysoft/PleromaPi#13]
I'm using [Latest nightly version](http://unofficialpi.org/Distros/PleromaPi/nightly/2022-02-05_pleromapi-20.04.3-preinstalled-server-arm64+raspi-0.3.0.zip)

Happening when creating new admin user thru command.

Error:
```ubuntu@pleromapi:~/scripts$ sudo docker exec pleroma /opt/pleroma/bin/pleroma_ctl user new thelatte example@mail.com –admin -y
** (MatchError) no match of right hand side value: {[assume_yes: true], ["–admin"], []}
    lib/mix/tasks/pleroma/user.ex:18: Mix.Tasks.Pleroma.User.run/1
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6```

**Comment by guysoft** [comment]
Hey, does the new user work?
Might be related to: 
https://git.pleroma.social/pleroma/pleroma/-/issues/2720

**Comment by guysoft** [comment]
Ok, I tested here locally and it seems to give me the same issue.
I reported it here:
https://git.pleroma.social/pleroma/pleroma/-/issues/2839

**Comment by guysoft** [comment]
Fixed

**Comment by litecave** [comment]
nice

**Comment by guysoft** [comment]
@litecave If you can test and report its working for you, I could release :)

**Comment by guysoft** [comment]
@litecave I hope its ok asking you again - any idea when you might test it?
\

**Comment by litecave** [comment]
yea, just didn't had time 'cuz unexpected IRL problems after messaging. I'm gonna test it rn.
