### ISSUE TITLE
Can not find Rust Compiler

### ISSUE THREAD

**Issue by stanhamil** [guysoft/PleromaPi#2]
The build proceeds normally but then provides a “error: Can not find Rust Compiler” message.
Debug assistance is provided on the screen but a subsequent message reads “ERROR: Failed building wheel for cryptography”
The build gets stuck on “Building wheel for pymacl (PEP 517): still running”.
Build fails.

**Comment by guysoft** [comment]
PleromaPi uses the official docker image to ship Pleroma.
What are you trying to build?

**Comment by guysoft** [comment]
This has been fixed. Docker module.in CustomPiOS could not find rust. 
https://github.com/guysoft/CustomPiOS/commit/8a70dd1c039961827518cd7496c6e0a2662fc534
