### ISSUE TITLE
enable configurable_from_database in your config file- enable by default

### ISSUE THREAD

**Issue by test2a** [guysoft/PleromaPi#5]
i got the website working thanks to you but i am having this error.
````
Request failed with status code 400 - You must enable configurable_from_database in your config file.
````

how about you enable this by default? is it necessary to default it to off ?

**Comment by guysoft** [comment]
Done https://git.pleroma.social/guysoft/pleroma-docker-compose/-/commit/a7c9ab408d0765f3dedcc8b58e4a6082812ebfb9
